# This is a copy of the `flake8` workflow at .github/workflows/flake8.yml
# but with autopep8 added in with a commit step to automate style checking
# and update the repo with the changes.
#
# It's separated because we don't want to push to the mainline branch
# on pull request, only when the change gets merged

name: Python Flake8 and Autopep8

on:
  push:
    branches: [ mainline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: In-place lint autopep8
      run: |
        autopep8 -ria api cdk iot_core scripts tests
    - name: Push code
      uses: actions-x/commit@v2
      with:
        name: makerspace-bot
        email: makerspace-bot@cumaker.space
        branch: mainline
        files: api cdk iot_core scripts tests
